// walletless-web-api/ClientApp/src/app/home/home.component.ts
import { Component } from '@angular/core';
import { User } from '../_models/user';
import { UserService } from '../_services/index';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
})
export class HomeComponent {
    currentUser: User;
    users: User[] = [];
 
    constructor(private userService: UserService) {
        this.currentUser = JSON.parse(localStorage.getItem('currentUser'));
    }
 
    ngOnInit() {
        this.loadAllUsers();
    }
 
    deleteUser(id: number) {
        this.userService.delete(id).subscribe(() => { this.loadAllUsers() });
    }
 
    private loadAllUsers() {
        this.userService.getAll().subscribe(users => { this.users = users; });
    }
}

<h1>Hello, welcome to WalletLess!</h1>
<p>Walletless is a consumer friendly App which enables users and healthcare
  providers to access stored information in a secure, convenient, accurate and
  timely manner. Users have immediate and easy access to a cyber wallet
  containing documents, insurance cards, and information that would normally be
  placed in wallets. Plus additional information can be stored limited only by the
  consumers imagination. Healthcare providers with consent from their patients
  can access authorized, accurate information and documents from the patient
  and, thereby, reduce one of its biggest problems, incomplete and inaccurate
  information. Walletless will also facilitate streamlined communication between
  healthcare providers, patients and insurance companies. The app will provide an
  unparalled retention and marketing tool for healthcare providers. Walletless is
  the opportunity to get an edge in the new consumer driven healthcare market.</p>
<ul>
  <li>Check out our mobile apps for <a href="">iOS</a>and <a href="">Android</a>!</li>
  <li>If you are a with a hosptal or insurance company, try <a href="">logging in</a>, or if you are new here, please <a href="">register</a>.</li>
  <li>We are not yet available for android, but we are coming soon!</li>
</ul>

// react-web/walletless-web-app/src/Home.js
import React, { Component } from "react";
 
class Home extends Component {
  render() {
    return (
      <div>
        <h2>Welcome to Walletless!</h2>
        <p>
            Walletless is a consumer-friendly app that enables users and healthcare providers
            to access stored information in a secure, convenient, accurate and timely manner.
            Users have immediate and easy access to a cyber wallet containing documents,
            insurance cards, and information that would normally be placed in wallets.
            Ultimately, additional information can be stored limited only by the imagination
            of the consumer. Healthcare providers with consent from their patients can
            access authorized, accurate information and documents from the patient and,
            thereby, reduce one of its biggest problems of incomplete and inaccurate
            information. Walletless will also facilitate streamlined communication between
            healthcare providers, patients and insurance companies. The app will provide an
            unparalled retention and marketing tool for healthcare providers. Walletless is
            the opportunity to get an edge in the new consumer driven healthcare market.
        </p>
 
        <p>Check out our <a>Mobile App!</a></p>
      </div>
    );
  }
}
 
export default Home;
